# Deploy the node server to HEROKU and the angular app to github pages


name: Full Stack Dev CI

on: [push]
  branches: [master]

jobs:
  deploy:
    name: Build and Deploy Node Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        # working-directory: ./backend
        with:
          heroku_api_key: ${{secrets.DIWALA_HEROKU_KEY}}
          heroku_app_name: "diwala-recruitment"
          heroku_email: "kathurimaroy@gmail.com"
          appdir: 'pizzeria/backend'
      # I think we can write the angular stuff here without having to specify another Job
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Setup the Angular Dependencies
        working-directory: ./pizzeria
        run: npm ci
      - name: Build the Angular FrontEnd
        working-directory: ./pizzeria
        run: npm run build:ci
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.DIWALA_GITHUB }}
          BRANCH: gh-pages
          FOLDER: pizzeria/dist/pizzeria
  # deploy_angular_app:
  #   name: Build and Deploy Angular App
  #   runs-on: